# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 724c392fb8b5036b18def9bc09ea07e2c3345693e1b433524850ba985144bed9f1ef0db387e8f52dad0d11a6653f9fe6ceb395d3dc541f7fe96d541a8f2b3bdb

test:
  secret_key_base: b5b8b3912375cef017492c96917290142897048dcf08377778b8e75134f6ac46e6bec7c11cbb68c41a5237f24d694506cf272cdb54598194f575e94569d389fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
